app.message: This message for the 'customers-service-recette.yml' file


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petclinic_dev?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    dialect: org.hibernate.dialect.MySQLDialect
    username: root
    password: admin

hibernate.dialect: hibernate.dialect
